### ISSUE TITLE
generate_cell_type_contact_count_matrices def in cell-cell contact analysis

### ISSUE THREAD

**Issue by ustc-fmh** [ZhuangLab/whole_mouse_brain_MERFISH_atlas_scripts_2023#3]
Hi, I'm reappearing cell cell contack analysis in your /cell_cell_contacts/randomize_and_count_cell_cell_contacts_30um.ipynb, but I can not load this function below:

sys.path.append('/home/xingjiepan/Softwares/ZhuangLab/MERFISH_analysis/cell_cell_contact')
from permutation import generate_cell_type_contact_count_matrices

Could you please publicly share the relevant functions? I would be greatly appreciative!

**Comment by watergua** [comment]
same issue here

**Comment by xingjiepan** [comment]
Please find the function here:
https://github.com/xingjiepan/MERFISH_analysis/blob/189059306d9537bf1bf455a603af69e0f7d944da/cell_cell_contact/permutation.py
